version: '3.7'

services:
  #Laravel + NGINX App
  rms_laravel_nginx:
    container_name: rms_laravel_nginx
    build:
      context: ./
      dockerfile: Dockerfile
    image: laravel-nginx-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - '8080:80'
    networks:
      - rms-network

  rms_db:
    container_name: rms_db
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    image: library/postgres:14
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - rms-data:/var/lib/postgresql/data/
    ports:
      - '54322:5432'
    networks:
      - rms-network

volumes:
  rms-data:

networks:
  rms-network:
    name: rms-network
    driver: bridge
